language: ruby
sudo: false
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.7
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - jruby-9.1.13.0
branches:
  only:
  - master
  - 2_stable
gemfile: Gemfile.travis
bundler_args: "--without development"
script: bundle exec rspec -fdoc
after_success: bundle exec codeclimate-test-reporter
env:
  global:
    secure: IT68W+OwNUzHqRc77nXA3iVbzGAnD3MGTBaXypT0ODDBVMKnMsAdCfH8QryBmtka1W7Is/1Tcb9sv8PqtBXNSoJPpJHYv6rXCJA1+nit0xvB1m4PXITrJOD2Kvj1KR7ovnQg9CG0pVxrPezKpHVDpPRzEkI79TMCrC5QTI4aZWU=
