language: ruby
sudo: false
rvm:
  - 3.0.0
  - 2.7.0
  - 2.6.4
  - 2.5.6
  - 2.4.6
  - truffleruby-head
branches:
  only:
  - master
  - 2_stable
  - 3_stable
gemfile: Gemfile.travis
bundler_args: "--without development"
script: bundle exec rspec -fdoc
before_install:
  - gem update --system
  - gem install bundler
after_success: bundle exec codeclimate-test-reporter
env:
  global:
    secure: IT68W+OwNUzHqRc77nXA3iVbzGAnD3MGTBaXypT0ODDBVMKnMsAdCfH8QryBmtka1W7Is/1Tcb9sv8PqtBXNSoJPpJHYv6rXCJA1+nit0xvB1m4PXITrJOD2Kvj1KR7ovnQg9CG0pVxrPezKpHVDpPRzEkI79TMCrC5QTI4aZWU=
